FROM node:18

# Create app directory
WORKDIR /home/ubuntu/inferencelgbm

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 8060

CMD [ "node", "frost-lgbm-wasm-server.js" ]
