version: '3.8'
services:
  webserver:
    image: webserver
    container_name: webserver
    environment:
      SENSORS_API_BASE: http://172.31.40.240:3000/
      PREDICTOR_TARGET: http://172.31.42.242:8060/
      STA_TARGET: http://172.31.32.79:3010/
    ports:
      - "8080:8080"
    restart: unless-stopped
