FROM node:18

# Create app directory
WORKDIR /home/ubuntu/apisec

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3000

CMD [ "node", "apiserver.js" ]
